// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the humanoid robotics textbook
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: The ROS2 Nervous System',
      items: [
        'module1-ros2/week1-introduction-to-ros2',
        'module1-ros2/week2-setting-up-ros2-workspace',
        'module1-ros2/week3-introduction-to-ros2-nervous-system',
        'module1-ros2/week4-ros2-communication-patterns',
        'module1-ros2/week5-advanced-ros2-concepts'
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin (Gazebo & Unity)',
      items: [
        'module2-digital-twin/week6-gazebo-simulation-fundamentals',
        'module2-digital-twin/week7-unity-hri-integration',
        'module2-digital-twin/week8-advanced-simulation-techniques'
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI Robot Brain (NVIDIA Isaac)',
      items: [
        'module3-isaac-brain/week9-introduction-to-isaac-slam',
        'module3-isaac-brain/week10-navigation-stack-path-planning',
        'module3-isaac-brain/week11-perception-and-object-detection'
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action Robotics',
      items: [
        'module4-vla-robotics/week12-introduction-to-vla-robotics',
        'module4-vla-robotics/week13-complete-vla-integration'
      ],
    },
    'capstone-project',
  ],
};

export default sidebars;
